# Generated by Django 4.1.7 on 2023-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(default=1, upload_to='myimage'),
            preserve_default=False,
        ),
    ]
